/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.s1n7ax.feedback;

import org.junit.Test;
/* import org.s1n7ax.feedback.Library; */

import static org.junit.Assert.*;

public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
//		Library classUnderTest = new Library();
//		assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
	}
}
